// create_directshape_from_mesh.cs
// Create a Revit DirectShape from raw mesh data (vertices + faces).
// The mesh data is passed as JSON with vertices in Revit internal units (feet).
//
// DirectShape is Revit's API for importing arbitrary mesh geometry that is
// natively visible but not parametrically editable — perfect for B-class
// complex components generated by TRELLIS (furniture, pipes, stairs, etc).
//
// @param parameters[0] (string) jsonStr - JSON object:
//   {
//     "name": "Chair #0",
//     "category": "OST_GenericModel",    // Revit built-in category
//     "vertices": [x0,y0,z0, x1,y1,z1, ...],  // flat array, feet (Revit internal)
//     "faces": [i0,i1,i2, i3,i4,i5, ...]      // flat triangle indices
//   }
// @returns { status, elementId, name, category, vertexCount, faceCount }
//
// Usage:
//   revit_send_code_to_revit(code=<this file>, parameters=['{"name":"Chair","category":"OST_GenericModel","vertices":[...],"faces":[...]}'])

using System;
using System.Collections.Generic;
using System.Linq;
using Autodesk.Revit.DB;

string jsonStr = Convert.ToString(parameters[0]);
var data = JsonConvert.DeserializeObject<Dictionary<string, object>>(jsonStr);

if (data == null)
    return new { error = "Invalid JSON" };

string dsName = data.ContainsKey("name") ? Convert.ToString(data["name"]) : "B-class Mesh";
string categoryStr = data.ContainsKey("category") ? Convert.ToString(data["category"]) : "OST_GenericModel";

// Parse vertices (flat [x,y,z, x,y,z, ...] in feet)
var vertsRaw = JsonConvert.DeserializeObject<List<double>>(data["vertices"].ToString());
if (vertsRaw == null || vertsRaw.Count < 9)
    return new { error = "Need at least 3 vertices (9 floats)" };

int vertexCount = vertsRaw.Count / 3;

// Parse faces (flat [i0,i1,i2, ...] triangle indices)
var facesRaw = JsonConvert.DeserializeObject<List<int>>(data["faces"].ToString());
if (facesRaw == null || facesRaw.Count < 3 || facesRaw.Count % 3 != 0)
    return new { error = "Faces must be triangle indices, count divisible by 3" };

int faceCount = facesRaw.Count / 3;

// --- Get category ---
BuiltInCategory bic;
try {
    bic = (BuiltInCategory)System.Enum.Parse(typeof(BuiltInCategory), categoryStr);
} catch {
    bic = BuiltInCategory.OST_GenericModel;
}
ElementId categoryId = new ElementId(bic);

// --- Get or create level ---
Level level = new FilteredElementCollector(document)
    .OfClass(typeof(Level))
    .Cast<Level>()
    .OrderBy(l => l.Elevation)
    .FirstOrDefault();

if (level == null) {
    level = Level.Create(document, 0);
    level.Name = "BIM-Recon Level 0";
}

// --- Build TessellatedShape from mesh data ---
// TessellatedShapeBuilder accepts raw triangles and builds a Revit solid or mesh.
var builder = new TessellatedShapeBuilder();

builder.OpenConnectedFaceSet(false);  // false = not solid (open shell)

for (int i = 0; i < faceCount; i++) {
    int i0 = facesRaw[i * 3];
    int i1 = facesRaw[i * 3 + 1];
    int i2 = facesRaw[i * 3 + 2];

    // Bounds check
    if (i0 >= vertexCount || i1 >= vertexCount || i2 >= vertexCount)
        continue;

    XYZ v0 = new XYZ(vertsRaw[i0 * 3], vertsRaw[i0 * 3 + 1], vertsRaw[i0 * 3 + 2]);
    XYZ v1 = new XYZ(vertsRaw[i1 * 3], vertsRaw[i1 * 3 + 1], vertsRaw[i1 * 3 + 2]);
    XYZ v2 = new XYZ(vertsRaw[i2 * 3], vertsRaw[i2 * 3 + 1], vertsRaw[i2 * 3 + 2]);

    // Skip degenerate triangles (zero area)
    double area = v1.Subtract(v0).CrossProduct(v2.Subtract(v0)).GetLength();
    if (area < 1e-9)
        continue;

    builder.AddFace(new TessellatedFace(v0, v1, v2, ElementId.InvalidElementId));
}

builder.CloseConnectedFaceSet();
builder.Target = TessellatedShapeBuilderTarget.Mesh;
builder.Fallback = TessellatedShapeBuilderFallback.Salvage;
builder.Build();

var result = builder.GetBuildResult();
if (result == null || result.GetGeometricalObjects().Count == 0)
    return new { error = "Failed to build tessellated shape from mesh data" };

// --- Create DirectShape ---
DirectShapeLibrary library = DirectShapeLibrary.GetDirectShapeLibrary(document);

// Check if a DirectShapeType with this name already exists
DirectShapeType dsType = null;
try {
    var existingTypes = new FilteredElementCollector(document)
        .OfClass(typeof(DirectShapeType))
        .Cast<DirectShapeType>()
        .FirstOrDefault(t => t.Name == dsName);
    dsType = existingTypes;
} catch { }

if (dsType == null) {
    dsType = DirectShapeLibrary.GetDirectShapeLibrary(document)
        .CreateDirectShapeType(dsName, categoryId, document);
}

// Add geometry to the type
var shapeList = result.GetGeometricalObjects().ToList();
dsType.SetShape(shapeList);

// Create the DirectShape instance
DirectShape ds = DirectShape.CreateElement(document, categoryId);
ds.SetTypeId(dsType.Id);
ds.Name = dsName;

return new {
    status = "ok",
    elementId = ds.Id.Value,
    name = dsName,
    category = categoryStr,
    vertexCount = vertexCount,
    faceCount = faceCount,
};
